# Github Action for hourly releases

name: CVE Yesterday's Delta Release

on:
  # at midnight (UTC) every night
  schedule:
    - cron: '0 0 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: false
        default: 'debug'
jobs:
  # setup:
  #   environment: deployment
  #   runs-on: ubuntu-latest
  #   outputs:
  #     v_current_run_timestamp: ${{ steps.get-timestamp.outputs.out }}
  #   steps:
  #     - name: util-id
  #       run: node ./.github/workflows/dist/index.js --version
  #     - name: generate-name
  #       id: get-timestamp
  #       run: echo "out=$(node ./.github/workflows/dist/index.js date --midnight-yesterday --terse)" >> $GITHUB_ENV
  create_release:
    # needs: [setup]
    environment: deployment
    runs-on: ubuntu-latest
    env:
      CVE_SERVICES_URL: https://cveawg.mitre.org
      CVES_BASE_DIRECTORY: cves
      CVES_RECENT_ACTIVITIES_FILENAME: recent_activities.json
      CVES_DEFAULT_UPDATE_LOOKBACK_IN_MINS: 180
      CVE_API_ORG: ${{secrets.CVE_API_ORG}}
      CVE_API_USER: ${{secrets.CVE_API_USER}}
      CVE_API_KEY: ${{secrets.CVE_API_KEY}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get utility version
        id: version
        run: node ./.github/workflows/dist/index.js --version
      - name: generate-name
        id: timestamp
        run: echo "timestamp=$(node ./.github/workflows/dist/index.js date --yesterday --terse)" >> $GITHUB_ENV
      - name: build delta files
        run: |
          ls ./.github/workflows/dist
          node ./.github/workflows/dist/index.js delta --yesterday-all
          echo "env.timestamp:"
          echo "${{ env.timestamp }}"
          echo "steps.version.outputs:"
          echo "${{ steps.version.outputs }}"
      - name: create release with source code as artifacts
        uses: softprops/action-gh-release@v1
        with:
          name: CVE2 ${{ env.timestamp }} at End of Day
          # body: Descriptions for CVE ${{ steps.timestamp.timestamp }} goes here
          body_path: ./release_notes.md
          tag_name: cve2_${{ env.timestamp }}_at_end_of_day
          files: |
            release_notes.md
            *.zip
