#!/bin/bash
# bash shell script that touches all CVEs in the target directory (param 1)
#    1. shifts cveMetadata.datePublished by 1 second, drops milliseconds and sets it to .999Z
# Note:
#   - the original code was generated by google gemini 3 pro

# Target directory (defaults to current dir if not provided)
TARGET_DIR="${1:-.}"

# keeps track of what the last processed CVE was so this script can be done in batches
STATE_FILE=".last_processed_cve"

# batch size
BATCH_SIZE=2

# check for jq
if ! command -v jq &> /dev/null; then
    echo "Error: jq is required but not installed."
    exit 1
fi

LAST_PROCESSED=""
if [ -f "$STATE_FILE" ]; then
    LAST_PROCESSED=$(cat "$STATE_FILE")
    echo "Resuming from: $LAST_PROCESSED"
else
    echo "No state file found. Starting from the beginning."
fi

echo "Starting recursive scan in: $TARGET_DIR"

# 1. Find all matching files recursively
# 2. Use a while loop to process them safely (handles spaces in filenames)
count=0

find "$TARGET_DIR" -type f -name 'CVE*.json' -print0 | while IFS= read -r -d '' file; do

    # 1. Write out filename
    echo "Processing: $file"

    # Check if the key exists before attempting modification
    if jq -e '.cveMetadata.datePublished' "$file" > /dev/null 2>&1; then
        
        # Create a temp file for the output
        tmp=$(mktemp)

        # 2. Parse, increment second, set microsecond to 999
        # This jq filter:
        # a. Takes the date string
        # b. Converts to seconds (fromdateiso8601)
        # c. Adds 1 second
        # d. Converts back to ISO string (todateiso8601)
        # e. Replaces the 'Z' at the end with '.999Z' to force the microseconds
        # jq '.cveMetadata.datePublished |= (fromdateiso8601 | . + 1 | todateiso8601 | sub("Z$"; ".999Z"))' "$file" > "$tmp"
        jq --indent 4 '.cveMetadata.datePublished |= (
            (if endswith("Z") then . else . + "Z" end) | # Ensure Z suffix exists
            sub("\\.[0-9]+Z$"; "Z") |                   # Strip existing milliseconds
            fromdateiso8601 |                           # Convert to Unix epoch
            . + 1 |                                     # Increment
            strftime("%Y-%m-%dT%H:%M:%S") |        # Format back to string
            . + ".999Z"                                 # Add your specific suffix
            )' "$file" > "$tmp"        
        # Move temp file back to original
        mv "$tmp" "$file"
    else
        # 3. Error message if key missing, output to stderr
        echo "Error: Key 'cveMetadata.datePublished' not found in $file" >&2
    fi

    # Batch tracking
    ((count++))
    if (( count % BATCH_SIZE == 0 )); then
        echo "--- Batch Complete: Processed $count files so far ---"
    fi

done

# update STATE_FILE
echo "$file" > "$STATE_FILE"

echo "Operation complete. Total files processed: $count"